version: '3.3'

services: 
    api:
        build: "./Golang-Server-A/Golang"
        ports:
            - "8080"
        restart: "always"
        networks: 
            - "api.network"
        deploy:
            replicas: 2
    
    server:
        build: "./Python-Server-A"
        ports:
            - "50051:50051"
        restart: "always"
        networks: 
            - "api.network"

    nginx:
        image: nginx:latest
        volumes:
            - ./Golang-Server-A/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api
        ports: 
            - "80:80"
        networks: 
            - "api.network"

networks: 
    api.network:

#docker-compose --compatibility up --build
#se accede mediant el puerto :80